#!/usr/bin/env bash
set -euo pipefail

APP_NAME="retrotransposon-miner"
INSTANCE_NAME="${INSTANCE_NAME:-}"
INSTANCE_ID="${INSTANCE_ID:-}"
INSTANCE_TYPE="${INSTANCE_TYPE:-r6i.4xlarge}"
HOST_ALIAS="${HOST_ALIAS:-retro-ec2}"
JLAB_ALIAS="${JLAB_ALIAS:-jlab}"
SSH_USER="${SSH_USER:-}"
JLAB_LOCAL_PORT="${JLAB_LOCAL_PORT:-8890}"
REGION="$(aws configure get region || true)"
REGION="${REGION:-us-east-1}"
SCRIPT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INSTANCE_STATE_FILE="${INSTANCE_STATE_FILE:-${REPO_ROOT}/.ec2-instance.env}"

mkdir -p "${HOME}/.ssh"
KEY_BASENAME="${APP_NAME}-${REGION}"
KEY_PATH_DEFAULT="${HOME}/.ssh/${KEY_BASENAME}.pem"
KEY_PATH="${KEY_PATH:-}"

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" >&2; }

load_instance_state() {
  [[ -f "${INSTANCE_STATE_FILE}" ]] || return 0
  local line key val
  while IFS= read -r line || [[ -n "${line}" ]]; do
    [[ "${line}" =~ ^[[:space:]]*# ]] && continue
    [[ "${line}" =~ ^([A-Za-z_][A-Za-z0-9_]*)=(.*)$ ]] || continue
    key="${BASH_REMATCH[1]}"
    val="${BASH_REMATCH[2]}"
    if [[ -z "${!key:-}" ]]; then
      export "${key}=${val}"
    fi
  done < "${INSTANCE_STATE_FILE}"
}

save_instance_state() {
  local iid="$1" name="$2" user="${3:-}"
  cat > "${INSTANCE_STATE_FILE}" <<EOF
# Generated by scripts/ec2_jlab.sh. Override with env vars or re-run use/bind-instance.
REGION=${REGION}
INSTANCE_ID=${iid}
INSTANCE_NAME=${name}
SSH_USER=${user}
EOF
  log "Saved instance binding to ${INSTANCE_STATE_FILE}"
}

load_instance_state

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || { echo "Missing command: $1"; exit 1; }
}

awsq() {
  aws --region "${REGION}" "$@"
}

imds_get() {
  local path="$1"
  local token
  token="$(curl -fsS -X PUT "http://169.254.169.254/latest/api/token" \
    -H "X-aws-ec2-metadata-token-ttl-seconds: 60" 2>/dev/null || true)"
  [[ -n "${token}" ]] || return 1
  curl -fsS "http://169.254.169.254/latest/${path}" \
    -H "X-aws-ec2-metadata-token: ${token}" 2>/dev/null
}

get_latest_al2023_ami() {
  awsq ssm get-parameter \
    --name /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64 \
    --query 'Parameter.Value' --output text
}

get_default_vpc() {
  awsq ec2 describe-vpcs \
    --filters Name=isDefault,Values=true \
    --query 'Vpcs[0].VpcId' --output text
}

get_default_subnet() {
  local vpc_id
  vpc_id="$(get_default_vpc)"
  awsq ec2 describe-subnets \
    --filters Name=vpc-id,Values="${vpc_id}" Name=default-for-az,Values=true \
    --query 'Subnets[0].SubnetId' --output text
}

ensure_key_pair() {
  local key_path="${KEY_PATH:-${KEY_PATH_DEFAULT}}"
  if [[ -f "${key_path}" ]]; then
    chmod 400 "${key_path}"
    log "Using existing key file: ${key_path}"
    return
  fi

  if awsq ec2 describe-key-pairs --key-names "${KEY_BASENAME}" >/dev/null 2>&1; then
    log "KeyPair '${KEY_BASENAME}' exists in AWS, but local PEM not found."
    log "Create/import a new key pair manually or delete old key pair and rerun."
    exit 1
  fi

  log "Creating key pair: ${KEY_BASENAME}"
  awsq ec2 create-key-pair \
    --key-name "${KEY_BASENAME}" \
    --query 'KeyMaterial' --output text > "${key_path}"
  chmod 400 "${key_path}"
}

ensure_security_group() {
  local vpc_id sg_name sg_id my_ip
  vpc_id="$(get_default_vpc)"
  sg_name="${APP_NAME}-ssh-sg"

  sg_id="$(awsq ec2 describe-security-groups \
    --filters Name=group-name,Values="${sg_name}" Name=vpc-id,Values="${vpc_id}" \
    --query 'SecurityGroups[0].GroupId' --output text 2>/dev/null || true)"

  if [[ -z "${sg_id}" || "${sg_id}" == "None" ]]; then
    log "Creating security group: ${sg_name}"
    sg_id="$(awsq ec2 create-security-group \
      --group-name "${sg_name}" \
      --description "SSH access for ${APP_NAME}" \
      --vpc-id "${vpc_id}" \
      --query 'GroupId' --output text)"
  fi

  my_ip="$(curl -s https://checkip.amazonaws.com)/32"
  log "Ensuring SSH ingress from ${my_ip} on ${sg_id}"
  awsq ec2 authorize-security-group-ingress \
    --group-id "${sg_id}" \
    --ip-permissions "IpProtocol=tcp,FromPort=22,ToPort=22,IpRanges=[{CidrIp=${my_ip},Description=local-ssh}]" \
    >/dev/null 2>&1 || true

  echo "${sg_id}"
}

public_ip_from_ssh_config() {
  local cfg="${HOME}/.ssh/config" host_ip
  [[ -f "${cfg}" ]] || return 1

  host_ip="$(
    awk -v host="${HOST_ALIAS}" '
      $1 == "Host" && $2 == host { in_block = 1; next }
      in_block && $1 == "Host" { in_block = 0 }
      in_block && $1 == "HostName" { print $2; exit }
    ' "${cfg}"
  )"
  if [[ -n "${host_ip}" && "${host_ip}" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "${host_ip}"
    return 0
  fi

  if command -v ssh >/dev/null 2>&1; then
    host_ip="$(ssh -G "${HOST_ALIAS}" 2>/dev/null | awk '$1=="hostname"{print $2; exit}' || true)"
    if [[ -n "${host_ip}" && "${host_ip}" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
      echo "${host_ip}"
      return 0
    fi
  fi

  return 1
}

instance_id_from_public_ip() {
  local host_ip="$1" iid
  [[ -n "${host_ip}" && "${host_ip}" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]] || return 1
  iid="$(
    awsq ec2 describe-instances \
      --filters Name=ip-address,Values="${host_ip}" Name=instance-state-name,Values=pending,running,stopping,stopped \
      --query 'Reservations[].Instances[].InstanceId' \
      --output text 2>/dev/null | awk 'NF{print $1; exit}'
  )"
  [[ -n "${iid}" && "${iid}" != "None" ]] || return 1
  echo "${iid}"
}

get_instance_id() {
  local iid host_ip

  if [[ -n "${INSTANCE_ID}" ]]; then
    echo "${INSTANCE_ID}"
    return 0
  fi

  if [[ -n "${INSTANCE_NAME}" ]]; then
    iid="$(
      awsq ec2 describe-instances \
        --filters Name=tag:Name,Values="${INSTANCE_NAME}" Name=instance-state-name,Values=pending,running,stopping,stopped \
        --query 'Reservations[].Instances[].InstanceId' \
        --output text 2>/dev/null | awk 'NF{print $1; exit}'
    )"
    if [[ -n "${iid}" && "${iid}" != "None" ]]; then
      echo "${iid}"
      return 0
    fi
  fi

  host_ip="$(public_ip_from_ssh_config || true)"
  iid="$(instance_id_from_public_ip "${host_ip}" || true)"
  if [[ -n "${iid}" ]]; then
    echo "${iid}"
    return 0
  fi

  if [[ -n "${APP_TAG:-}" ]]; then
    iid="$(
      awsq ec2 describe-instances \
        --filters Name=tag:App,Values="${APP_TAG}" Name=instance-state-name,Values=pending,running,stopping,stopped \
        --query 'Reservations[].Instances[].InstanceId' \
        --output text 2>/dev/null | awk 'NF{print $1; exit}'
    )"
    if [[ -n "${iid}" && "${iid}" != "None" ]]; then
      echo "${iid}"
      return 0
    fi
  fi

  iid="$(imds_get "meta-data/instance-id" || true)"
  if [[ -n "${iid}" ]]; then
    echo "${iid}"
    return 0
  fi

  return 1
}

resolve_instance_name() {
  local iid="$1" name
  name="$(awsq ec2 describe-instances \
    --instance-ids "${iid}" \
    --query 'Reservations[0].Instances[0].Tags[?Key==`Name`]|[0].Value' \
    --output text 2>/dev/null || true)"
  if [[ -n "${name}" && "${name}" != "None" ]]; then
    echo "${name}"
    return 0
  fi
  if [[ -n "${INSTANCE_NAME}" ]]; then
    echo "${INSTANCE_NAME}"
    return 0
  fi
  echo "${iid}"
}

resolve_instance_selector() {
  local sel="$1" iid
  [[ -n "${sel}" ]] || return 1

  if [[ "${sel}" =~ ^i-[0-9a-f]+$ ]]; then
    echo "${sel}"
    return 0
  fi

  iid="$(
    awsq ec2 describe-instances \
      --filters Name=tag:Name,Values="${sel}" Name=instance-state-name,Values=pending,running,stopping,stopped \
      --query 'Reservations[].Instances[].InstanceId' \
      --output text 2>/dev/null | awk 'NF{print $1; exit}'
  )"
  if [[ -n "${iid}" && "${iid}" != "None" ]]; then
    echo "${iid}"
    return 0
  fi

  log "No instance found for selector: ${sel}"
  return 1
}

resolve_ssh_user() {
  local iid="$1" ami image_name
  if [[ -n "${SSH_USER}" ]]; then
    echo "${SSH_USER}"
    return 0
  fi

  ami="$(awsq ec2 describe-instances \
    --instance-ids "${iid}" \
    --query 'Reservations[0].Instances[0].ImageId' \
    --output text 2>/dev/null || true)"
  if [[ -n "${ami}" && "${ami}" != "None" ]]; then
    image_name="$(awsq ec2 describe-images \
      --image-ids "${ami}" \
      --query 'Images[0].Name' \
      --output text 2>/dev/null || true)"
    if [[ "${image_name}" == *ubuntu* ]]; then
      echo "ubuntu"
      return 0
    fi
    if [[ "${image_name}" == *debian* ]]; then
      echo "admin"
      return 0
    fi
  fi

  echo "ec2-user"
}

require_instance_id() {
  local iid
  iid="$(get_instance_id || true)"
  if [[ -z "${iid}" ]]; then
    log "No instance bound."
    log "  $0 list-instances"
    log "  $0 use <instance-id-or-name>"
    exit 1
  fi
  echo "${iid}"
}

instance_not_bound_help() {
  log "No instance bound."
  log "  $0 list-instances"
  log "  $0 use <instance-id-or-name>"
}

default_create_instance_name() {
  if [[ -n "${INSTANCE_NAME}" ]]; then
    echo "${INSTANCE_NAME}"
    return 0
  fi
  echo "${APP_NAME}-${INSTANCE_TYPE}-$(date +%Y%m%d%H%M%S)"
}

bind_instance() {
  local sel="${1:-${INSTANCE_ID:-}}" iid
  [[ -n "${sel}" ]] || {
    log "Usage: $0 use <instance-id-or-name>"
    log "List candidates with: $0 list-instances"
    exit 1
  }

  iid="$(resolve_instance_selector "${sel}")" || exit 1

  awsq ec2 describe-instances --instance-ids "${iid}" >/dev/null 2>&1 || {
    log "Instance not found in ${REGION}: ${iid}"
    exit 1
  }

  INSTANCE_ID="${iid}"
  export INSTANCE_ID
  write_ssh_config
  log "Bound ${iid}. Start with: $0 up"
}

create_instance() {
  local instance_id ami subnet sg_id create_name
  ami="$(get_latest_al2023_ami)"
  subnet="$(get_default_subnet)"
  sg_id="$(ensure_security_group)"
  ensure_key_pair

  create_name="$(default_create_instance_name)"
  log "Creating instance ${create_name} (${INSTANCE_TYPE})"
  instance_id="$(awsq ec2 run-instances \
    --image-id "${ami}" \
    --instance-type "${INSTANCE_TYPE}" \
    --key-name "${KEY_BASENAME}" \
    --subnet-id "${subnet}" \
    --security-group-ids "${sg_id}" \
    --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=${create_name}},{Key=App,Value=${APP_NAME}}]" \
    --count 1 \
    --query 'Instances[0].InstanceId' --output text)"

  save_instance_state "${instance_id}" "${create_name}" "$(resolve_ssh_user "${instance_id}")"
  echo "${instance_id}"
}

ensure_instance() {
  local instance_id
  instance_id="$(get_instance_id || true)"

  if [[ -n "${instance_id}" ]]; then
    log "Found existing instance: ${instance_id}"
    echo "${instance_id}"
    return
  fi

  create_instance
}

start_instance() {
  local iid
  iid="$(require_instance_id)"
  log "Starting instance ${iid}"
  awsq ec2 start-instances --instance-ids "${iid}" >/dev/null 2>&1 || true
  awsq ec2 wait instance-running --instance-ids "${iid}"
  awsq ec2 wait instance-status-ok --instance-ids "${iid}"
  log "Instance is running and healthy."
}

up() {
  local sel="${1:-}"
  [[ -n "${sel}" ]] && bind_instance "${sel}"
  start_instance
  write_ssh_config
  status
  log "Connect: ssh ${HOST_ALIAS}"
}

connect() {
  up "${1:-}"
  exec ssh "${HOST_ALIAS}"
}

stop_instance() {
  local iid
  iid="$(require_instance_id)"
  log "Stopping ${iid}"
  if ! awsq ec2 stop-instances --instance-ids "${iid}" >/dev/null 2>&1; then
    log "Unable to stop via EC2 API with current credentials."
    log "If you're currently on this EC2 host, use: sudo shutdown -h now"
    exit 1
  fi
  awsq ec2 wait instance-stopped --instance-ids "${iid}"
  log "Instance stopped."
}

reboot_instance() {
  local iid
  iid="$(require_instance_id)"
  log "Rebooting ${iid}"
  awsq ec2 reboot-instances --instance-ids "${iid}"
  awsq ec2 wait instance-status-ok --instance-ids "${iid}"
  log "Instance healthy after reboot."
}

ensure_eip() {
  local iid alloc_id assoc_id
  iid="$(require_instance_id)"

  local eip_tag="${APP_NAME}-${iid}-eip"
  alloc_id="$(awsq ec2 describe-addresses \
    --filters Name=tag:Name,Values="${eip_tag}" \
    --query 'Addresses[0].AllocationId' --output text 2>/dev/null || true)"

  if [[ -z "${alloc_id}" || "${alloc_id}" == "None" ]]; then
    alloc_id="$(awsq ec2 describe-addresses \
      --filters Name=instance-id,Values="${iid}" \
      --query 'Addresses[0].AllocationId' --output text 2>/dev/null || true)"
  fi

  if [[ -z "${alloc_id}" || "${alloc_id}" == "None" ]]; then
    log "Allocating Elastic IP"
    alloc_id="$(awsq ec2 allocate-address --domain vpc --query 'AllocationId' --output text)"
    awsq ec2 create-tags --resources "${alloc_id}" --tags "Key=Name,Value=${eip_tag}" "Key=App,Value=${APP_NAME}" >/dev/null
  fi

  log "Associating EIP ${alloc_id} to ${iid}"
  assoc_id="$(awsq ec2 associate-address --instance-id "${iid}" --allocation-id "${alloc_id}" --allow-reassociation --query 'AssociationId' --output text)"
  log "EIP association: ${assoc_id}"
}

get_public_ip_for() {
  local iid="$1" ip
  ip="$(awsq ec2 describe-instances \
    --instance-ids "${iid}" \
    --query 'Reservations[0].Instances[0].PublicIpAddress' \
    --output text)"
  [[ -n "${ip}" && "${ip}" != "None" ]] || return 1
  echo "${ip}"
}

get_public_ip() {
  local iid
  iid="$(get_instance_id)" || return 1
  get_public_ip_for "${iid}"
}

resolve_identity_file() {
  local key_name="$1" candidate dir
  if [[ -n "${KEY_PATH}" && -f "${KEY_PATH}" ]]; then
    echo "${KEY_PATH}"
    return
  fi
  if [[ -f "${HOME}/.ssh/${key_name}.pem" ]]; then
    echo "${HOME}/.ssh/${key_name}.pem"
    return
  fi
  for dir in "${HOME}/Documents/git" "${HOME}/Dropbox/Mac/Documents/git"; do
    [[ -d "${dir}" ]] || continue
    candidate="$(find "${dir}" -maxdepth 5 -name "${key_name}.pem" 2>/dev/null | head -1)"
    if [[ -n "${candidate}" && -f "${candidate}" ]]; then
      echo "${candidate}"
      return
    fi
  done
  if [[ "${key_name}" == "${KEY_BASENAME}" && -f "${KEY_PATH_DEFAULT}" ]]; then
    echo "${KEY_PATH_DEFAULT}"
    return
  fi
  echo "${HOME}/.ssh/${key_name}.pem"
}

ensure_instance_ssh_ingress() {
  local iid="$1" my_ip sg_id
  my_ip="$(curl -fsS --max-time 5 https://checkip.amazonaws.com)/32"
  while read -r sg_id; do
    [[ -n "${sg_id}" ]] || continue
    awsq ec2 authorize-security-group-ingress \
      --group-id "${sg_id}" \
      --ip-permissions "IpProtocol=tcp,FromPort=22,ToPort=22,IpRanges=[{CidrIp=${my_ip},Description=local-ssh}]" \
      >/dev/null 2>&1 || true
  done < <(awsq ec2 describe-instances \
    --instance-ids "${iid}" \
    --query 'Reservations[0].Instances[0].SecurityGroups[].GroupId' \
    --output text | tr '\t' '\n')
}

ssh_proxy() {
  local port="${1:-22}" ip iid
  load_instance_state
  iid="$(get_instance_id)" || {
    instance_not_bound_help
    exit 1
  }
  ensure_instance_ssh_ingress "${iid}"
  ip="$(get_public_ip_for "${iid}")" || { log "No public IP for ${iid}"; exit 1; }
  exec nc "${ip}" "${port}"
}

write_ssh_config() {
  local iid name cfg key_name identity_file ssh_user
  iid="$(get_instance_id)" || {
    instance_not_bound_help
    exit 1
  }
  name="$(resolve_instance_name "${iid}")"
  ssh_user="$(resolve_ssh_user "${iid}")"
  save_instance_state "${iid}" "${name}" "${ssh_user}"
  key_name="$(awsq ec2 describe-instances \
    --instance-ids "${iid}" \
    --query 'Reservations[0].Instances[0].KeyName' \
    --output text)"
  identity_file="$(resolve_identity_file "${key_name}")"
  cfg="${HOME}/.ssh/config"
  touch "${cfg}"

  awk -v host_alias="${HOST_ALIAS}" -v jlab_alias="${JLAB_ALIAS}" '
    BEGIN{skip=0}
    $0 ~ "^Host " host_alias "$" {skip=1; next}
    $0 ~ "^Host " jlab_alias "$" {skip=1; next}
    /^Host / {skip=0}
    skip==0 {print}
  ' "${cfg}" > "${cfg}.tmp"
  mv "${cfg}.tmp" "${cfg}"

  cat >> "${cfg}" <<EOF

Host ${HOST_ALIAS}
  HostName ${HOST_ALIAS}
  User ${ssh_user}
  IdentityFile ${identity_file}
  IdentitiesOnly yes
  ProxyCommand ${SCRIPT_PATH} ssh-proxy %p
  ConnectTimeout 30
  ServerAliveInterval 15
  ServerAliveCountMax 4
  TCPKeepAlive yes
  StrictHostKeyChecking accept-new

Host ${JLAB_ALIAS}
  HostName ${JLAB_ALIAS}
  User ${ssh_user}
  IdentityFile ${identity_file}
  IdentitiesOnly yes
  ProxyCommand ${SCRIPT_PATH} ssh-proxy %p
  LocalForward ${JLAB_LOCAL_PORT} 127.0.0.1:8888
  ConnectTimeout 30
  ServerAliveInterval 15
  ServerAliveCountMax 4
  TCPKeepAlive yes
  StrictHostKeyChecking accept-new
EOF

  log "Updated ${cfg} for ${iid} (${name}) using ${identity_file}."
}

start_jlab() {
  ssh "${HOST_ALIAS}" "python3 -m pip -q install --user jupyterlab >/dev/null 2>&1 || true; mkdir -p ~/.jlab; [ -f ~/.jlab/token ] || openssl rand -hex 24 > ~/.jlab/token; TOKEN=\$(cat ~/.jlab/token); nohup jupyter lab --no-browser --ip 127.0.0.1 --port 8888 --ServerApp.token=\"\$TOKEN\" > ~/jupyter.log 2>&1 & sleep 3; echo \"TOKEN=\$TOKEN\"; jupyter server list"
}

stop_jlab() {
  ssh "${HOST_ALIAS}" "pkill -f 'jupyter-lab|jupyter lab' || true"
  log "JupyterLab stopped."
}

start_tunnel() {
  pkill -f "ssh -N ${JLAB_ALIAS}" >/dev/null 2>&1 || true
  nohup ssh -N "${JLAB_ALIAS}" >/tmp/jlab-tunnel.log 2>&1 &
  sleep 1
  log "Tunnel running on http://127.0.0.1:${JLAB_LOCAL_PORT}"
}

status() {
  local iid
  iid="$(get_instance_id || true)"
  if [[ -z "${iid}" ]]; then
    instance_not_bound_help
    exit 0
  fi
  awsq ec2 describe-instances \
    --instance-ids "${iid}" \
    --query 'Reservations[0].Instances[0].{InstanceId:InstanceId,State:State.Name,PublicIp:PublicIpAddress,Type:InstanceType,Name:Tags[?Key==`Name`]|[0].Value}' \
    --output table
}

list_instances() {
  awsq ec2 describe-instances \
    --filters Name=instance-state-name,Values=pending,running,stopping,stopped \
    --query 'sort_by(Reservations[].Instances[], &LaunchTime)[].{InstanceId:InstanceId,State:State.Name,Name:Tags[?Key==`Name`]|[0].Value,Type:InstanceType,PublicIp:PublicIpAddress,LaunchTime:LaunchTime}' \
    --output table
}

bootstrap() {
  require_cmd aws
  require_cmd ssh
  require_cmd curl

  ensure_key_pair
  ensure_security_group >/dev/null
  ensure_instance >/dev/null
  start_instance
  ensure_eip
  write_ssh_config
  status
  start_jlab
  start_tunnel

  local token
  token="$(ssh "${HOST_ALIAS}" "cat ~/.jlab/token")"
  echo
  echo "Open JupyterLab:"
  echo "http://127.0.0.1:${JLAB_LOCAL_PORT}/lab?token=${token}"
}

usage() {
  cat <<EOF
Usage: $0 <command> [args]

Bring your own EC2 (typical):
  $0 list-instances
  $0 use <instance-id-or-name>
  $0 up
  ssh ${HOST_ALIAS}

One-shot start + SSH config:
  $0 up <instance-id-or-name>
  $0 connect [instance-id-or-name]

Lifecycle:
  status | start-instance | stop-instance | reboot-instance

JupyterLab:
  start-jlab | stop-jlab | start-tunnel

Create a new EC2 for this project:
  bootstrap

Optional env vars:
  REGION, INSTANCE_ID, INSTANCE_NAME, HOST_ALIAS, SSH_USER, KEY_PATH
EOF
}

case "${1:-help}" in
  help|-h|--help) usage ;;
  bootstrap) bootstrap ;;
  use|bind-instance) bind_instance "${2:-}" ;;
  up) up "${2:-}" ;;
  connect) connect "${2:-}" ;;
  list-instances) list_instances ;;
  start-instance) start_instance ;;
  stop-instance) stop_instance ;;
  reboot-instance) reboot_instance ;;
  ensure-eip) ensure_eip ;;
  ssh-config) write_ssh_config ;;
  resolve-ip) get_public_ip ;;
  ssh-proxy)
    if [[ "${2:-}" =~ ^i-[0-9a-f]+$ ]]; then
      ssh_proxy "${3:-22}"
    else
      ssh_proxy "${2:-22}"
    fi
    ;;
  start-jlab) start_jlab ;;
  stop-jlab) stop_jlab ;;
  start-tunnel) start_tunnel ;;
  status) status ;;
  *)
    usage
    exit 1
    ;;
esac
