#!/usr/bin/env bash
set -euo pipefail

APP_NAME="retrotransposon-miner"
INSTANCE_NAME="${INSTANCE_NAME:-}"
INSTANCE_ID="${INSTANCE_ID:-}"
AMI_ID="${AMI_ID:-}"
INSTANCE_TYPE="${INSTANCE_TYPE:-r6i.4xlarge}"
ROOT_VOLUME_GB="${ROOT_VOLUME_GB:-200}"
# gp3 throughput/IOPS are independently provisioned, but AWS requires
# throughput (MB/s) <= 0.25 * IOPS. 1000 MB/s therefore needs >= 4000 IOPS.
# Default 125 MB/s is the WGS stage bottleneck on r6i.4xlarge (EBS max 1250).
ROOT_VOLUME_IOPS="${ROOT_VOLUME_IOPS:-4000}"
ROOT_VOLUME_THROUGHPUT_MB="${ROOT_VOLUME_THROUGHPUT_MB:-1000}"
S3_BUCKET="${S3_BUCKET:-}"
S3_CACHE_PREFIX="${S3_CACHE_PREFIX:-}"
IAM_INSTANCE_PROFILE="${IAM_INSTANCE_PROFILE:-ec2-retrotransposon-s3-profile}"
IAM_ROLE_NAME="${IAM_ROLE_NAME:-ec2-retrotransposon-s3-role}"
HOST_ALIAS="${HOST_ALIAS:-retro-ec2}"
JLAB_ALIAS="${JLAB_ALIAS:-jlab}"
SSH_USER="${SSH_USER:-}"
JLAB_LOCAL_PORT="${JLAB_LOCAL_PORT:-8890}"
REGION="$(aws configure get region || true)"
REGION="${REGION:-us-east-1}"
SCRIPT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INSTANCE_STATE_FILE="${INSTANCE_STATE_FILE:-${REPO_ROOT}/.ec2-instance.env}"

mkdir -p "${HOME}/.ssh"
KEY_NAME="${KEY_NAME:-}"
KEY_OWNER="${KEY_OWNER:-}"
KEY_BASENAME="${KEY_BASENAME:-}"
KEY_PATH="${KEY_PATH:-}"
KEY_PATH_DEFAULT=""

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" >&2; }

load_instance_state() {
  [[ -f "${INSTANCE_STATE_FILE}" ]] || return 0
  local line key val
  while IFS= read -r line || [[ -n "${line}" ]]; do
    [[ "${line}" =~ ^[[:space:]]*# ]] && continue
    [[ "${line}" =~ ^([A-Za-z_][A-Za-z0-9_]*)=(.*)$ ]] || continue
    key="${BASH_REMATCH[1]}"
    val="${BASH_REMATCH[2]}"
    if [[ -z "${!key:-}" ]]; then
      export "${key}=${val}"
    fi
  done < "${INSTANCE_STATE_FILE}"
}

save_instance_state() {
  local iid="$1" name="$2" user="${3:-}"
  cat > "${INSTANCE_STATE_FILE}" <<EOF
# Generated by scripts/ec2_jlab.sh. Override with env vars or re-run use/bind-instance.
REGION=${REGION}
INSTANCE_ID=${iid}
INSTANCE_NAME=${name}
SSH_USER=${user}
S3_BUCKET=${S3_BUCKET}
S3_CACHE_PREFIX=${S3_CACHE_PREFIX}
IAM_INSTANCE_PROFILE=${IAM_INSTANCE_PROFILE}
IAM_ROLE_NAME=${IAM_ROLE_NAME}
KEY_PATH=${KEY_PATH}
KEY_BASENAME=${KEY_BASENAME}
EOF
  log "Saved instance binding to ${INSTANCE_STATE_FILE}"
}

load_instance_state

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || { echo "Missing command: $1"; exit 1; }
}

awsq() {
  aws --region "${REGION}" "$@"
}

imds_get() {
  local path="$1"
  local token
  token="$(curl -fsS -X PUT "http://169.254.169.254/latest/api/token" \
    -H "X-aws-ec2-metadata-token-ttl-seconds: 60" 2>/dev/null || true)"
  [[ -n "${token}" ]] || return 1
  curl -fsS "http://169.254.169.254/latest/${path}" \
    -H "X-aws-ec2-metadata-token: ${token}" 2>/dev/null
}

# --- AMI selection --------------------------------------------------------
# Resolution order used by bootstrap (and the internal test hook below):
#   1. AMI_ID override: validated via describe-images, never queries SSM.
#   2. Public SSM parameter (AL2023 kernel-default x86_64); the returned value
#      is syntax-checked rather than trusted blindly.
#   3. ec2 describe-images fallback: Amazon-owned, AL2023 kernel 6.1, x86_64,
#      EBS-backed, available; newest by CreationDate; then fully validated.
# Only the resolved AMI id is ever printed to stdout; diagnostics go to stderr.
AL2023_SSM_PARAM="/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64"
AL2023_IMAGE_NAME_PATTERN="al2023-ami-2023.*-kernel-6.1-x86_64"

ami_valid_syntax() {
  [[ "$1" =~ ^ami-[0-9a-f]+$ ]]
}

get_latest_al2023_ami() {
  local out rc
  out="$(awsq ssm get-parameter --name "${AL2023_SSM_PARAM}" --query 'Parameter.Value' --output text 2>&1)" && rc=0 || rc=$?
  if [[ "${rc}" -eq 0 && "${out}" =~ ^ami-[0-9a-f]+$ ]]; then
    echo "${out}"
    return 0
  fi
  if [[ "${rc}" -eq 0 ]]; then
    if [[ -z "${out}" || "${out}" == "None" ]]; then
      log "  ssm get-parameter returned no value."
    else
      log "  ssm get-parameter returned a malformed value: ${out}"
    fi
  else
    log "  ssm get-parameter exited ${rc}:"
    sed 's/^/    /' <<< "${out}" >&2 || true
  fi
  return 1
}

validate_selected_ami() {
  local ami="$1" out rc img state arch rootdev
  if ! ami_valid_syntax "${ami}"; then
    log "Invalid AMI id ${ami}; expected an id like ami-0<hex>."
    return 1
  fi
  out="$(awsq ec2 describe-images \
    --owners amazon \
    --image-ids "${ami}" \
    --query 'Images[0].[ImageId,State,Architecture,RootDeviceType]' \
    --output text 2>&1)" && rc=0 || rc=$?
  if [[ "${rc}" -ne 0 ]]; then
    if [[ "${out}" == *InvalidAMIID.NotFound* ]]; then
      log "AMI ${ami} does not exist."
    else
      log "Unable to validate AMI ${ami}:"
      sed 's/^/  /' <<< "${out}" >&2 || true
    fi
    return 1
  fi
  if [[ -z "${out}" || "${out}" == "None" ]]; then
    log "AMI ${ami} does not exist or is not Amazon-owned."
    return 1
  fi
  IFS=$'\t' read -r img state arch rootdev <<< "${out}"
  [[ "${img}" == "${ami}" ]] || {
    log "AMI validation mismatch for ${ami}."
    return 1
  }
  [[ "${state}" == "available" ]] || {
    log "AMI ${ami} is not available (state=${state})."
    return 1
  }
  [[ "${arch}" == "x86_64" ]] || {
    log "AMI ${ami} is not x86_64 (architecture=${arch})."
    return 1
  }
  [[ "${rootdev}" == "ebs" ]] || {
    log "AMI ${ami} is not EBS-backed (root-device-type=${rootdev})."
    return 1
  }
  echo "${ami}"
  return 0
}

ami_fallback_ec2() {
  local out rc
  out="$(awsq ec2 describe-images \
    --owners amazon \
    --filters \
      "Name=name,Values=${AL2023_IMAGE_NAME_PATTERN}" \
      "Name=architecture,Values=x86_64" \
      "Name=root-device-type,Values=ebs" \
      "Name=state,Values=available" \
    --query "sort_by(Images, &CreationDate)[-1].ImageId" \
    --output text 2>&1)" && rc=0 || rc=$?
  if [[ "${rc}" -ne 0 ]]; then
    log "  ec2 describe-images exited ${rc}:"
    sed 's/^/    /' <<< "${out}" >&2 || true
    return 1
  fi
  if [[ -z "${out}" || "${out}" == "None" ]]; then
    log "  No Amazon Linux 2023 image matches the fallback filters."
    return 1
  fi
  if ! ami_valid_syntax "${out}"; then
    log "  ec2 describe-images returned a malformed AMI id: ${out}"
    return 1
  fi
  echo "${out}"
  return 0
}

resolve_ami() {
  local ami validated sel

  if [[ -n "${AMI_ID}" ]]; then
    validated="$(validate_selected_ami "${AMI_ID}")" || return 1
    echo "${validated}"
    return 0
  fi

  if ami="$(get_latest_al2023_ami)"; then
    echo "${ami}"
    return 0
  fi

  log "ssm get-parameter did not yield a usable AMI; using ec2 describe-images fallback."
  if sel="$(ami_fallback_ec2)"; then
    validated="$(validate_selected_ami "${sel}")" && {
      echo "${validated}"
      return 0
    }
    log "  ec2 describe-images selected an invalid AMI: ${sel}"
  fi

  log "Could not determine an Amazon Linux 2023 x86_64 AMI id."
  log "Set AMI_ID to an approved Amazon Linux 2023 x86_64 AMI id (Amazon-owned, x86_64, EBS-backed) and re-run:"
  log "  AMI_ID=ami-<id> $0 bootstrap"
  return 1
}

get_default_vpc() {
  awsq ec2 describe-vpcs \
    --filters Name=isDefault,Values=true \
    --query 'Vpcs[0].VpcId' --output text
}

get_default_subnet() {
  local vpc_id
  vpc_id="$(get_default_vpc)"
  awsq ec2 describe-subnets \
    --filters Name=vpc-id,Values="${vpc_id}" Name=default-for-az,Values=true \
    --query 'Subnets[0].SubnetId' --output text
}

sanitize_key_token() {
  echo "$1" | tr -c 'A-Za-z0-9+=.@_-' '-' | sed -E 's/-+/-/g; s/^-//; s/-$//'
}

aws_identity_user() {
  local arn user
  if [[ -n "${KEY_OWNER}" ]]; then
    sanitize_key_token "${KEY_OWNER}"
    return
  fi
  arn="$(aws sts get-caller-identity --query Arn --output text 2>/dev/null || true)"
  if [[ "${arn}" == *":user/"* ]]; then
    user="${arn##*:user/}"
  elif [[ "${arn}" == *":assumed-role/"* ]]; then
    user="$(printf '%s\n' "${arn}" | awk -F/ '{print $2}')"
  else
    user="$(id -un 2>/dev/null || echo local)"
  fi
  sanitize_key_token "${user}"
}

resolve_key_basename() {
  if [[ -n "${KEY_NAME}" ]]; then
    echo "${KEY_NAME}"
    return
  fi
  if [[ -n "${KEY_BASENAME}" ]]; then
    echo "${KEY_BASENAME}"
    return
  fi
  echo "${APP_NAME}-${REGION}-$(aws_identity_user)"
}

first_local_pubkey() {
  local f
  for f in "${HOME}/.ssh/id_ed25519.pub" "${HOME}/.ssh/id_rsa.pub"; do
    [[ -f "${f}" ]] || continue
    echo "${f}"
    return 0
  done
  return 1
}

key_pair_exists() {
  awsq ec2 describe-key-pairs --key-names "$1" >/dev/null 2>&1
}

import_pubkey_as_key_pair() {
  local name="$1" pub="$2"
  if key_pair_exists "${name}"; then
    log "Reusing EC2 key pair ${name}"
    return 0
  fi
  log "Importing $(basename "${pub}") as EC2 key pair ${name}"
  awsq ec2 import-key-pair \
    --key-name "${name}" \
    --public-key-material "fileb://${pub}" >/dev/null
}

ensure_key_pair() {
  KEY_BASENAME="$(resolve_key_basename)"
  KEY_PATH_DEFAULT="${HOME}/.ssh/${KEY_BASENAME}.pem"
  export KEY_BASENAME
  local key_path="${KEY_PATH:-}" pub priv

  if [[ -n "${key_path}" && -f "${key_path}" ]]; then
    chmod 400 "${key_path}" 2>/dev/null || true
    if [[ -f "${key_path}.pub" ]]; then
      import_pubkey_as_key_pair "${KEY_BASENAME}" "${key_path}.pub"
    fi
    log "Using existing key file: ${key_path}"
    return
  fi

  if pub="$(first_local_pubkey)"; then
    priv="${pub%.pub}"
    import_pubkey_as_key_pair "${KEY_BASENAME}" "${pub}"
    KEY_PATH="${priv}"
    export KEY_PATH
    log "Using laptop SSH key: ${KEY_PATH} (key pair ${KEY_BASENAME})"
    return
  fi

  key_path="${KEY_PATH_DEFAULT}"
  if [[ -f "${key_path}" ]]; then
    if ! key_pair_exists "${KEY_BASENAME}"; then
      log "Local PEM ${key_path} exists but AWS has no key pair ${KEY_BASENAME}."
      log "Run: ssh-keygen -t ed25519   then rerun bootstrap so your .pub can be imported."
      exit 1
    fi
    KEY_PATH="${key_path}"
    export KEY_PATH
    chmod 400 "${key_path}"
    log "Using existing key file: ${key_path}"
    return
  fi

  if key_pair_exists "${KEY_BASENAME}"; then
    log "Key pair ${KEY_BASENAME} exists in AWS, but this laptop has no matching private key."
    log "Generate one with: ssh-keygen -t ed25519"
    log "Then rerun bootstrap (it will import ~/.ssh/id_ed25519.pub as your key pair)."
    exit 1
  fi

  log "Creating key pair: ${KEY_BASENAME}"
  awsq ec2 create-key-pair \
    --key-name "${KEY_BASENAME}" \
    --query 'KeyMaterial' --output text > "${key_path}"
  chmod 400 "${key_path}"
  KEY_PATH="${key_path}"
  export KEY_PATH
}

ensure_security_group() {
  local vpc_id sg_name sg_id my_ip
  vpc_id="$(get_default_vpc)"
  sg_name="${APP_NAME}-ssh-sg"

  sg_id="$(awsq ec2 describe-security-groups \
    --filters Name=group-name,Values="${sg_name}" Name=vpc-id,Values="${vpc_id}" \
    --query 'SecurityGroups[0].GroupId' --output text 2>/dev/null || true)"

  if [[ -z "${sg_id}" || "${sg_id}" == "None" ]]; then
    log "Creating security group: ${sg_name}"
    sg_id="$(awsq ec2 create-security-group \
      --group-name "${sg_name}" \
      --description "SSH access for ${APP_NAME}" \
      --vpc-id "${vpc_id}" \
      --query 'GroupId' --output text)"
  fi

  my_ip="$(curl -s https://checkip.amazonaws.com)/32"
  log "Ensuring SSH ingress from ${my_ip} on ${sg_id}"
  awsq ec2 authorize-security-group-ingress \
    --group-id "${sg_id}" \
    --ip-permissions "IpProtocol=tcp,FromPort=22,ToPort=22,IpRanges=[{CidrIp=${my_ip},Description=local-ssh}]" \
    >/dev/null 2>&1 || true

  echo "${sg_id}"
}

s3_bucket_name() {
  local raw="${1:-}"
  raw="${raw#s3://}"
  raw="${raw%%/*}"
  echo "${raw}"
}

s3_bucket_uri() {
  local name
  name="$(s3_bucket_name "$1")"
  [[ -n "${name}" ]] || return 1
  echo "s3://${name}"
}

s3_cache_prefix_for() {
  if [[ -n "${S3_CACHE_PREFIX}" ]]; then
    local p="${S3_CACHE_PREFIX}"
    [[ "${p}" == s3://* ]] || p="s3://${p}"
    echo "${p%/}"
    return 0
  fi
  local name
  name="$(s3_bucket_name "$1")"
  [[ -n "${name}" ]] || return 1
  echo "s3://${name}/public"
}

ensure_s3_bucket() {
  local name="$1"
  [[ -n "${name}" ]] || return 0
  if awsq s3api head-bucket --bucket "${name}" >/dev/null 2>&1; then
    log "Using S3 bucket s3://${name}"
    return 0
  fi
  log "Creating S3 bucket s3://${name} in ${REGION}"
  if [[ "${REGION}" == "us-east-1" ]]; then
    awsq s3api create-bucket --bucket "${name}" >/dev/null
  else
    awsq s3api create-bucket --bucket "${name}" \
      --create-bucket-configuration "LocationConstraint=${REGION}" >/dev/null
  fi
}

ensure_iam_instance_profile_for_bucket() {
  local bucket="$1" trust policy_file policy_name has_role created=0
  [[ -n "${bucket}" ]] || return 0

  if aws iam get-role --role-name "${IAM_ROLE_NAME}" >/dev/null 2>&1 \
    && aws iam get-instance-profile --instance-profile-name "${IAM_INSTANCE_PROFILE}" >/dev/null 2>&1; then
    has_role="$(aws iam get-instance-profile \
      --instance-profile-name "${IAM_INSTANCE_PROFILE}" \
      --query 'InstanceProfile.Roles[0].RoleName' --output text 2>/dev/null || true)"
    if [[ -n "${has_role}" && "${has_role}" != "None" ]]; then
      log "Reusing instance role ${IAM_ROLE_NAME} / profile ${IAM_INSTANCE_PROFILE} (no IAM policy updates)"
      return 0
    fi
  fi

  trust='{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Principal":{"Service":"ec2.amazonaws.com"},"Action":"sts:AssumeRole"}]}'
  if ! aws iam get-role --role-name "${IAM_ROLE_NAME}" >/dev/null 2>&1; then
    log "Creating IAM role ${IAM_ROLE_NAME}"
    aws iam create-role \
      --role-name "${IAM_ROLE_NAME}" \
      --assume-role-policy-document "${trust}" >/dev/null
    created=1
  fi

  if ! aws iam get-instance-profile --instance-profile-name "${IAM_INSTANCE_PROFILE}" >/dev/null 2>&1; then
    log "Creating instance profile ${IAM_INSTANCE_PROFILE}"
    aws iam create-instance-profile --instance-profile-name "${IAM_INSTANCE_PROFILE}" >/dev/null
    created=1
  fi

  has_role="$(aws iam get-instance-profile \
    --instance-profile-name "${IAM_INSTANCE_PROFILE}" \
    --query 'InstanceProfile.Roles[0].RoleName' --output text 2>/dev/null || true)"
  if [[ -z "${has_role}" || "${has_role}" == "None" ]]; then
    log "Attaching role ${IAM_ROLE_NAME} to profile ${IAM_INSTANCE_PROFILE}"
    aws iam add-role-to-instance-profile \
      --instance-profile-name "${IAM_INSTANCE_PROFILE}" \
      --role-name "${IAM_ROLE_NAME}" >/dev/null
    created=1
  fi

  policy_name="s3-bucket-${bucket}"
  policy_file="$(mktemp)"
  cat > "${policy_file}" <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "ListBucket",
      "Effect": "Allow",
      "Action": ["s3:ListBucket", "s3:GetBucketLocation"],
      "Resource": "arn:aws:s3:::${bucket}"
    },
    {
      "Sid": "ObjectRW",
      "Effect": "Allow",
      "Action": [
        "s3:GetObject",
        "s3:PutObject",
        "s3:DeleteObject",
        "s3:AbortMultipartUpload",
        "s3:ListMultipartUploadParts"
      ],
      "Resource": "arn:aws:s3:::${bucket}/*"
    }
  ]
}
EOF
  log "Granting ${IAM_ROLE_NAME} read/write on s3://${bucket}"
  aws iam put-role-policy \
    --role-name "${IAM_ROLE_NAME}" \
    --policy-name "${policy_name}" \
    --policy-document "file://${policy_file}" >/dev/null
  rm -f "${policy_file}"

  if [[ "${created}" == "1" ]]; then
    log "Waiting for instance profile to propagate"
    sleep 10
  fi
}

write_remote_s3_env() {
  local bucket_uri cache
  [[ -n "${S3_BUCKET}" ]] || return 0
  bucket_uri="$(s3_bucket_uri "${S3_BUCKET}")"
  cache="$(s3_cache_prefix_for "${S3_BUCKET}")"
  log "Writing ${cache} onto ${HOST_ALIAS} as RTM_S3_CACHE"
  ssh "${HOST_ALIAS}" "mkdir -p ~/.config/rtm; printf '%s\n' 'RTM_S3_CACHE=${cache}' 'RTM_S3_BUCKET=${bucket_uri}' > ~/.config/rtm/s3.env; touch ~/.bashrc; grep -q 'config/rtm/s3.env' ~/.bashrc || echo 'set -a; [ -f \"\$HOME/.config/rtm/s3.env\" ] && . \"\$HOME/.config/rtm/s3.env\"; set +a' >> ~/.bashrc"
}

attach_instance_profile() {
  local iid assoc cache bucket_name
  [[ -n "${S3_BUCKET}" ]] || {
    log "Set S3_BUCKET (e.g. S3_BUCKET=s3://<your-bucket>) to attach instance S3 access."
    exit 1
  }
  bucket_name="$(s3_bucket_name "${S3_BUCKET}")"
  S3_BUCKET="$(s3_bucket_uri "${S3_BUCKET}")"
  S3_CACHE_PREFIX="$(s3_cache_prefix_for "${S3_BUCKET}")"
  cache="${S3_CACHE_PREFIX}"
  export S3_BUCKET S3_CACHE_PREFIX

  ensure_s3_bucket "${bucket_name}"
  ensure_iam_instance_profile_for_bucket "${bucket_name}"
  iid="$(require_instance_id)"

  awsq ec2 create-tags --resources "${iid}" \
    --tags "Key=S3Bucket,Value=${bucket_name}" "Key=S3CachePrefix,Value=${cache}" >/dev/null

  assoc="$(awsq ec2 describe-iam-instance-profile-associations \
    --filters "Name=instance-id,Values=${iid}" \
    --query 'IamInstanceProfileAssociations[0].AssociationId' --output text 2>/dev/null || true)"
  if [[ -z "${assoc}" || "${assoc}" == "None" ]]; then
    log "Associating instance profile ${IAM_INSTANCE_PROFILE} with ${iid}"
    awsq ec2 associate-iam-instance-profile \
      --instance-id "${iid}" \
      --iam-instance-profile "Name=${IAM_INSTANCE_PROFILE}" >/dev/null
  else
    log "Replacing instance profile on ${iid} with ${IAM_INSTANCE_PROFILE}"
    awsq ec2 replace-iam-instance-profile-association \
      --association-id "${assoc}" \
      --iam-instance-profile "Name=${IAM_INSTANCE_PROFILE}" >/dev/null
  fi

  save_instance_state "${iid}" "$(resolve_instance_name "${iid}")" "$(resolve_ssh_user "${iid}")"
  write_remote_s3_env || log "Could not write remote S3 env yet (SSH may not be ready)."
  log "Instance can use ${S3_BUCKET} via IAM role ${IAM_ROLE_NAME} (not your local AWS keys)."
  log "Public-data cache prefix: ${cache}"
}

build_s3_user_data() {
  local cache bucket_uri
  cache="$(s3_cache_prefix_for "${S3_BUCKET}")"
  bucket_uri="$(s3_bucket_uri "${S3_BUCKET}")"
  cat <<EOF
#!/bin/bash
set -euo pipefail
install -d -o ec2-user -g ec2-user /home/ec2-user/.config/rtm
printf '%s\n' 'RTM_S3_CACHE=${cache}' 'RTM_S3_BUCKET=${bucket_uri}' > /home/ec2-user/.config/rtm/s3.env
chown ec2-user:ec2-user /home/ec2-user/.config/rtm/s3.env
touch /home/ec2-user/.bashrc
grep -q 'config/rtm/s3.env' /home/ec2-user/.bashrc || echo 'set -a; [ -f "\$HOME/.config/rtm/s3.env" ] && . "\$HOME/.config/rtm/s3.env"; set +a' >> /home/ec2-user/.bashrc
EOF
}

public_ip_from_ssh_config() {
  local cfg="${HOME}/.ssh/config" host_ip
  [[ -f "${cfg}" ]] || return 1

  host_ip="$(
    awk -v host="${HOST_ALIAS}" '
      $1 == "Host" && $2 == host { in_block = 1; next }
      in_block && $1 == "Host" { in_block = 0 }
      in_block && $1 == "HostName" { print $2; exit }
    ' "${cfg}"
  )"
  if [[ -n "${host_ip}" && "${host_ip}" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "${host_ip}"
    return 0
  fi

  if command -v ssh >/dev/null 2>&1; then
    host_ip="$(ssh -G "${HOST_ALIAS}" 2>/dev/null | awk '$1=="hostname"{print $2; exit}' || true)"
    if [[ -n "${host_ip}" && "${host_ip}" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
      echo "${host_ip}"
      return 0
    fi
  fi

  return 1
}

instance_id_from_public_ip() {
  local host_ip="$1" iid
  [[ -n "${host_ip}" && "${host_ip}" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]] || return 1
  iid="$(
    awsq ec2 describe-instances \
      --filters Name=ip-address,Values="${host_ip}" Name=instance-state-name,Values=pending,running,stopping,stopped \
      --query 'Reservations[].Instances[].InstanceId' \
      --output text 2>/dev/null | awk 'NF{print $1; exit}'
  )"
  [[ -n "${iid}" && "${iid}" != "None" ]] || return 1
  echo "${iid}"
}

get_instance_id() {
  local iid host_ip

  if [[ -n "${INSTANCE_ID}" ]]; then
    echo "${INSTANCE_ID}"
    return 0
  fi

  if [[ -n "${INSTANCE_NAME}" ]]; then
    iid="$(
      awsq ec2 describe-instances \
        --filters Name=tag:Name,Values="${INSTANCE_NAME}" Name=instance-state-name,Values=pending,running,stopping,stopped \
        --query 'Reservations[].Instances[].InstanceId' \
        --output text 2>/dev/null | awk 'NF{print $1; exit}'
    )"
    if [[ -n "${iid}" && "${iid}" != "None" ]]; then
      echo "${iid}"
      return 0
    fi
  fi

  host_ip="$(public_ip_from_ssh_config || true)"
  iid="$(instance_id_from_public_ip "${host_ip}" || true)"
  if [[ -n "${iid}" ]]; then
    echo "${iid}"
    return 0
  fi

  if [[ -n "${APP_TAG:-}" ]]; then
    iid="$(
      awsq ec2 describe-instances \
        --filters Name=tag:App,Values="${APP_TAG}" Name=instance-state-name,Values=pending,running,stopping,stopped \
        --query 'Reservations[].Instances[].InstanceId' \
        --output text 2>/dev/null | awk 'NF{print $1; exit}'
    )"
    if [[ -n "${iid}" && "${iid}" != "None" ]]; then
      echo "${iid}"
      return 0
    fi
  fi

  iid="$(imds_get "meta-data/instance-id" || true)"
  if [[ -n "${iid}" ]]; then
    echo "${iid}"
    return 0
  fi

  return 1
}

resolve_instance_name() {
  local iid="$1" name
  name="$(awsq ec2 describe-instances \
    --instance-ids "${iid}" \
    --query 'Reservations[0].Instances[0].Tags[?Key==`Name`]|[0].Value' \
    --output text 2>/dev/null || true)"
  if [[ -n "${name}" && "${name}" != "None" ]]; then
    echo "${name}"
    return 0
  fi
  if [[ -n "${INSTANCE_NAME}" ]]; then
    echo "${INSTANCE_NAME}"
    return 0
  fi
  echo "${iid}"
}

resolve_instance_selector() {
  local sel="$1" iid
  [[ -n "${sel}" ]] || return 1

  if [[ "${sel}" =~ ^i-[0-9a-f]+$ ]]; then
    echo "${sel}"
    return 0
  fi

  iid="$(
    awsq ec2 describe-instances \
      --filters Name=tag:Name,Values="${sel}" Name=instance-state-name,Values=pending,running,stopping,stopped \
      --query 'Reservations[].Instances[].InstanceId' \
      --output text 2>/dev/null | awk 'NF{print $1; exit}'
  )"
  if [[ -n "${iid}" && "${iid}" != "None" ]]; then
    echo "${iid}"
    return 0
  fi

  log "No instance found for selector: ${sel}"
  return 1
}

resolve_ssh_user() {
  local iid="$1" ami image_name
  if [[ -n "${SSH_USER}" ]]; then
    echo "${SSH_USER}"
    return 0
  fi

  ami="$(awsq ec2 describe-instances \
    --instance-ids "${iid}" \
    --query 'Reservations[0].Instances[0].ImageId' \
    --output text 2>/dev/null || true)"
  if [[ -n "${ami}" && "${ami}" != "None" ]]; then
    image_name="$(awsq ec2 describe-images \
      --image-ids "${ami}" \
      --query 'Images[0].Name' \
      --output text 2>/dev/null || true)"
    if [[ "${image_name}" == *ubuntu* ]]; then
      echo "ubuntu"
      return 0
    fi
    if [[ "${image_name}" == *debian* ]]; then
      echo "admin"
      return 0
    fi
  fi

  echo "ec2-user"
}

require_instance_id() {
  local iid
  iid="$(get_instance_id || true)"
  if [[ -z "${iid}" ]]; then
    log "No instance bound."
    log "  $0 list-instances"
    log "  $0 use <instance-id-or-name>"
    exit 1
  fi
  echo "${iid}"
}

instance_not_bound_help() {
  log "No instance bound."
  log "  $0 list-instances"
  log "  $0 use <instance-id-or-name>"
}

default_create_instance_name() {
  if [[ -n "${INSTANCE_NAME}" ]]; then
    echo "${INSTANCE_NAME}"
    return 0
  fi
  echo "${APP_NAME}-${INSTANCE_TYPE}-$(date +%Y%m%d%H%M%S)"
}

bind_instance() {
  local sel="${1:-${INSTANCE_ID:-}}" iid
  [[ -n "${sel}" ]] || {
    log "Usage: $0 use <instance-id-or-name>"
    log "List candidates with: $0 list-instances"
    exit 1
  }

  iid="$(resolve_instance_selector "${sel}")" || exit 1

  awsq ec2 describe-instances --instance-ids "${iid}" >/dev/null 2>&1 || {
    log "Instance not found in ${REGION}: ${iid}"
    exit 1
  }

  INSTANCE_ID="${iid}"
  export INSTANCE_ID
  write_ssh_config
  log "Bound ${iid}. Start with: $0 up"
}

create_instance() {
  local instance_id ami subnet sg_id create_name bucket_name ud_file="" tags
  local -a run_args
  ami="$(resolve_ami)" || exit 1
  [[ "${ami}" =~ ^ami-[0-9a-f]+$ ]] || {
    log "No usable AMI id; aborting before run-instances."
    exit 1
  }
  subnet="$(get_default_subnet)"
  sg_id="$(ensure_security_group)"
  ensure_key_pair

  create_name="$(default_create_instance_name)"
  tags="[{Key=Name,Value=${create_name}},{Key=App,Value=${APP_NAME}}]"
  if [[ -n "${S3_BUCKET}" ]]; then
    bucket_name="$(s3_bucket_name "${S3_BUCKET}")"
    S3_BUCKET="$(s3_bucket_uri "${S3_BUCKET}")"
    S3_CACHE_PREFIX="$(s3_cache_prefix_for "${S3_BUCKET}")"
    export S3_BUCKET S3_CACHE_PREFIX
    ensure_s3_bucket "${bucket_name}"
    ensure_iam_instance_profile_for_bucket "${bucket_name}"
    ud_file="$(mktemp)"
    build_s3_user_data > "${ud_file}"
    tags="[{Key=Name,Value=${create_name}},{Key=App,Value=${APP_NAME}},{Key=S3Bucket,Value=${bucket_name}},{Key=S3CachePrefix,Value=${S3_CACHE_PREFIX}}]"
  fi

  log "Creating instance ${create_name} (${INSTANCE_TYPE})"
  run_args=(
    --image-id "${ami}"
    --instance-type "${INSTANCE_TYPE}"
    --key-name "${KEY_BASENAME}"
    --subnet-id "${subnet}"
    --security-group-ids "${sg_id}"
    --block-device-mappings "DeviceName=/dev/xvda,Ebs={VolumeSize=${ROOT_VOLUME_GB},VolumeType=gp3,Iops=${ROOT_VOLUME_IOPS},Throughput=${ROOT_VOLUME_THROUGHPUT_MB},DeleteOnTermination=true}"
    --tag-specifications "ResourceType=instance,Tags=${tags}"
    --count 1
    --query "Instances[0].InstanceId"
    --output text
  )
  if [[ -n "${S3_BUCKET}" ]]; then
    run_args+=(--iam-instance-profile "Name=${IAM_INSTANCE_PROFILE}")
    run_args+=(--user-data "file://${ud_file}")
  fi
  instance_id="$(awsq ec2 run-instances "${run_args[@]}")"
  [[ -n "${ud_file}" ]] && rm -f "${ud_file}"

  INSTANCE_ID="${instance_id}"
  INSTANCE_NAME="${create_name}"
  export INSTANCE_ID INSTANCE_NAME
  save_instance_state "${instance_id}" "${create_name}" "$(resolve_ssh_user "${instance_id}")"
  echo "${instance_id}"
}

ensure_instance() {
  local instance_id
  instance_id="$(get_instance_id || true)"

  if [[ -n "${instance_id}" ]]; then
    log "Found existing instance: ${instance_id}"
    echo "${instance_id}"
    return
  fi

  create_instance
}

instance_missing_diagnostic() {
  local iid="$1"
  log "Selected instance no longer exists: ${iid}"
  log "  $0 list-instances"
  log "  $0 use <instance-id-or-name>"
  log "  Stale binding kept at ${INSTANCE_STATE_FILE}; rebind to a live instance (use) or create a new one (bootstrap)."
}

# probe_instance reports whether instance ${iid} exists, without mislabeling
# other API failures (auth/network/throttle) as "missing".
#   returns 0 = describe-instances succeeded (instance exists)
#   returns 2 = InvalidInstanceID.NotFound (instance definitively gone)
#   returns 1 = describe-instances failed for another reason
probe_instance() {
  local iid="$1"
  PROBE_ERR="$(awsq ec2 describe-instances --instance-ids "${iid}" 2>&1 >/dev/null || true)"
  if [[ -z "${PROBE_ERR}" ]]; then
    return 0
  fi
  if grep -q "InvalidInstanceID.NotFound" <<<"${PROBE_ERR}"; then
    return 2
  fi
  return 1
}

handle_missing_or_probe_failure() {
  local iid="$1" rc="$2"
  if [[ "${rc}" -eq 2 ]]; then
    instance_missing_diagnostic "${iid}"
  else
    log "Unable to query instance ${iid}."
    sed 's/^/  /' <<< "${PROBE_ERR}" >&2 || true
    log "Check AWS credentials and connectivity, then re-run: $0 status"
  fi
  exit 1
}

start_instance() {
  local iid rc err

  require_cmd aws

  iid="$(require_instance_id)"

  # The bound instance may have been terminated since the state file was written;
  # fail fast rather than letting a hung wait look like a successful start.
  rc=0
  probe_instance "${iid}" || rc=$?
  [[ "${rc}" -eq 0 ]] || handle_missing_or_probe_failure "${iid}" "${rc}"

  log "Starting instance ${iid}"
  if ! err="$(awsq ec2 start-instances --instance-ids "${iid}" 2>&1 >/dev/null)"; then
    log "Failed to start instance ${iid}:"
    sed 's/^/  /' <<< "${err}" >&2 || true
    exit 1
  fi

  if ! awsq ec2 wait instance-running --instance-ids "${iid}" >/dev/null 2>&1; then
    rc=0
    probe_instance "${iid}" || rc=$?
    if [[ "${rc}" -eq 0 ]]; then
      log "Instance ${iid} did not reach the running state."
      log "Check current state with: $0 status"
      exit 1
    fi
    handle_missing_or_probe_failure "${iid}" "${rc}"
  fi

  if ! awsq ec2 wait instance-status-ok --instance-ids "${iid}" >/dev/null 2>&1; then
    rc=0
    probe_instance "${iid}" || rc=$?
    if [[ "${rc}" -eq 0 ]]; then
      log "Instance ${iid} is running but not status-ok yet."
      log "Check status with: $0 status"
      exit 1
    fi
    handle_missing_or_probe_failure "${iid}" "${rc}"
  fi

  log "Instance is running and healthy."
}

up() {
  local sel="${1:-}"
  [[ -n "${sel}" ]] && bind_instance "${sel}"
  start_instance
  write_ssh_config
  status
  log "Connect: ssh ${HOST_ALIAS}"
}

connect() {
  up "${1:-}"
  exec ssh "${HOST_ALIAS}"
}

stop_instance() {
  local iid
  iid="$(require_instance_id)"
  log "Stopping ${iid}"
  if ! awsq ec2 stop-instances --instance-ids "${iid}" >/dev/null 2>&1; then
    log "Unable to stop via EC2 API with current credentials."
    log "If you're currently on this EC2 host, use: sudo shutdown -h now"
    exit 1
  fi
  awsq ec2 wait instance-stopped --instance-ids "${iid}"
  log "Instance stopped."
}

reboot_instance() {
  local iid
  iid="$(require_instance_id)"
  log "Rebooting ${iid}"
  awsq ec2 reboot-instances --instance-ids "${iid}"
  awsq ec2 wait instance-status-ok --instance-ids "${iid}"
  log "Instance healthy after reboot."
}

ensure_eip() {
  local iid alloc_id assoc_id
  iid="$(require_instance_id)"

  local eip_tag="${APP_NAME}-${iid}-eip"
  alloc_id="$(awsq ec2 describe-addresses \
    --filters Name=tag:Name,Values="${eip_tag}" \
    --query 'Addresses[0].AllocationId' --output text 2>/dev/null || true)"

  if [[ -z "${alloc_id}" || "${alloc_id}" == "None" ]]; then
    alloc_id="$(awsq ec2 describe-addresses \
      --filters Name=instance-id,Values="${iid}" \
      --query 'Addresses[0].AllocationId' --output text 2>/dev/null || true)"
  fi

  if [[ -z "${alloc_id}" || "${alloc_id}" == "None" ]]; then
    log "Allocating Elastic IP"
    alloc_id="$(awsq ec2 allocate-address --domain vpc --query 'AllocationId' --output text)"
    awsq ec2 create-tags --resources "${alloc_id}" --tags "Key=Name,Value=${eip_tag}" "Key=App,Value=${APP_NAME}" >/dev/null
  fi

  log "Associating EIP ${alloc_id} to ${iid}"
  assoc_id="$(awsq ec2 associate-address --instance-id "${iid}" --allocation-id "${alloc_id}" --allow-reassociation --query 'AssociationId' --output text)"
  log "EIP association: ${assoc_id}"
}

get_public_ip_for() {
  local iid="$1" ip
  ip="$(awsq ec2 describe-instances \
    --instance-ids "${iid}" \
    --query 'Reservations[0].Instances[0].PublicIpAddress' \
    --output text)"
  [[ -n "${ip}" && "${ip}" != "None" ]] || return 1
  echo "${ip}"
}

get_public_ip() {
  local iid
  iid="$(get_instance_id)" || return 1
  get_public_ip_for "${iid}"
}

resolve_identity_file() {
  local key_name="$1" pub priv
  if [[ -n "${KEY_PATH}" && -f "${KEY_PATH}" ]]; then
    echo "${KEY_PATH}"
    return
  fi
  if [[ -f "${HOME}/.ssh/${key_name}.pem" ]]; then
    echo "${HOME}/.ssh/${key_name}.pem"
    return
  fi
  if [[ -n "${KEY_PATH_DEFAULT}" && -f "${KEY_PATH_DEFAULT}" ]]; then
    echo "${KEY_PATH_DEFAULT}"
    return
  fi
  if pub="$(first_local_pubkey)"; then
    priv="${pub%.pub}"
    if [[ -f "${priv}" ]]; then
      echo "${priv}"
      return
    fi
  fi
  echo "${HOME}/.ssh/${key_name}.pem"
}

instance_az() {
  local iid="$1"
  awsq ec2 describe-instances \
    --instance-ids "${iid}" \
    --query 'Reservations[0].Instances[0].Placement.AvailabilityZone' \
    --output text
}

install_my_key() {
  local iid ssh_user pub priv ip az line
  require_cmd aws
  require_cmd ssh
  iid="$(require_instance_id)"
  pub="$(first_local_pubkey)" || {
    log "No ~/.ssh/id_ed25519.pub or ~/.ssh/id_rsa.pub on this laptop."
    log "Create one with: ssh-keygen -t ed25519"
    exit 1
  }
  priv="${pub%.pub}"
  [[ -f "${priv}" ]] || { log "Found ${pub} but no private key ${priv}"; exit 1; }
  ssh_user="$(resolve_ssh_user "${iid}")"
  ip="$(get_public_ip_for "${iid}")" || { log "No public IP for ${iid}. Start it first: $0 up"; exit 1; }
  az="$(instance_az "${iid}")"
  ensure_instance_ssh_ingress "${iid}"
  log "Pushing $(basename "${pub}") via EC2 Instance Connect (${az})"
  awsq ec2-instance-connect send-ssh-public-key \
    --instance-id "${iid}" \
    --availability-zone "${az}" \
    --instance-os-user "${ssh_user}" \
    --ssh-public-key "file://${pub}" >/dev/null
  line="$(tr -d '\n' < "${pub}")"
  ssh -i "${priv}" -o IdentitiesOnly=yes -o StrictHostKeyChecking=accept-new \
    -o ConnectTimeout=15 \
    "${ssh_user}@${ip}" \
    "mkdir -p ~/.ssh && chmod 700 ~/.ssh && touch ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys && grep -qF '${line}' ~/.ssh/authorized_keys || echo '${line}' >> ~/.ssh/authorized_keys"
  KEY_PATH="${priv}"
  export KEY_PATH
  write_ssh_config
  log "Installed your public key on ${iid}. Connect with: ssh ${HOST_ALIAS}"
}

ensure_instance_ssh_ingress() {
  local iid="$1" my_ip sg_id
  my_ip="$(curl -fsS --max-time 5 https://checkip.amazonaws.com)/32"
  while read -r sg_id; do
    [[ -n "${sg_id}" ]] || continue
    awsq ec2 authorize-security-group-ingress \
      --group-id "${sg_id}" \
      --ip-permissions "IpProtocol=tcp,FromPort=22,ToPort=22,IpRanges=[{CidrIp=${my_ip},Description=local-ssh}]" \
      >/dev/null 2>&1 || true
  done < <(awsq ec2 describe-instances \
    --instance-ids "${iid}" \
    --query 'Reservations[0].Instances[0].SecurityGroups[].GroupId' \
    --output text | tr '\t' '\n')
}

ssh_proxy() {
  local port="${1:-22}" ip iid
  load_instance_state
  iid="$(get_instance_id)" || {
    instance_not_bound_help
    exit 1
  }
  ensure_instance_ssh_ingress "${iid}"
  ip="$(get_public_ip_for "${iid}")" || { log "No public IP for ${iid}"; exit 1; }
  exec nc "${ip}" "${port}"
}

write_ssh_config() {
  local iid name cfg key_name identity_file ssh_user
  iid="$(get_instance_id)" || {
    instance_not_bound_help
    exit 1
  }
  name="$(resolve_instance_name "${iid}")"
  ssh_user="$(resolve_ssh_user "${iid}")"
  save_instance_state "${iid}" "${name}" "${ssh_user}"
  key_name="$(awsq ec2 describe-instances \
    --instance-ids "${iid}" \
    --query 'Reservations[0].Instances[0].KeyName' \
    --output text)"
  identity_file="$(resolve_identity_file "${key_name}")"
  cfg="${HOME}/.ssh/config"
  touch "${cfg}"

  awk -v host_alias="${HOST_ALIAS}" -v jlab_alias="${JLAB_ALIAS}" '
    BEGIN{skip=0}
    $0 ~ "^Host " host_alias "$" {skip=1; next}
    $0 ~ "^Host " jlab_alias "$" {skip=1; next}
    /^Host / {skip=0}
    skip==0 {print}
  ' "${cfg}" > "${cfg}.tmp"
  mv "${cfg}.tmp" "${cfg}"

  cat >> "${cfg}" <<EOF

Host ${HOST_ALIAS}
  HostName ${HOST_ALIAS}
  User ${ssh_user}
  IdentityFile ${identity_file}
  IdentitiesOnly yes
  ProxyCommand ${SCRIPT_PATH} ssh-proxy %p
  ConnectTimeout 30
  ServerAliveInterval 15
  ServerAliveCountMax 4
  TCPKeepAlive yes
  StrictHostKeyChecking accept-new

Host ${JLAB_ALIAS}
  HostName ${JLAB_ALIAS}
  User ${ssh_user}
  IdentityFile ${identity_file}
  IdentitiesOnly yes
  ProxyCommand ${SCRIPT_PATH} ssh-proxy %p
  LocalForward ${JLAB_LOCAL_PORT} 127.0.0.1:8888
  ConnectTimeout 30
  ServerAliveInterval 15
  ServerAliveCountMax 4
  TCPKeepAlive yes
  StrictHostKeyChecking accept-new
EOF

  log "Updated ${cfg} for ${iid} (${name}) using ${identity_file}."
}

start_jlab() {
  ssh "${HOST_ALIAS}" "python3 -m pip -q install --user jupyterlab >/dev/null 2>&1 || true; mkdir -p ~/.jlab; [ -f ~/.jlab/token ] || openssl rand -hex 24 > ~/.jlab/token; TOKEN=\$(cat ~/.jlab/token); nohup jupyter lab --no-browser --ip 127.0.0.1 --port 8888 --ServerApp.token=\"\$TOKEN\" > ~/jupyter.log 2>&1 & sleep 3; echo \"TOKEN=\$TOKEN\"; jupyter server list"
}

stop_jlab() {
  ssh "${HOST_ALIAS}" "pkill -f 'jupyter-lab|jupyter lab' || true"
  log "JupyterLab stopped."
}

start_tunnel() {
  local token i=0
  pkill -f "ssh -N ${JLAB_ALIAS}" >/dev/null 2>&1 || true
  nohup ssh -N "${JLAB_ALIAS}" >/tmp/jlab-tunnel.log 2>&1 &
  while (( i < 30 )); do
    if lsof -nP -iTCP:"${JLAB_LOCAL_PORT}" -sTCP:LISTEN >/dev/null 2>&1; then
      token="$(ssh "${HOST_ALIAS}" "cat ~/.jlab/token 2>/dev/null" || true)"
      log "Tunnel running on http://127.0.0.1:${JLAB_LOCAL_PORT}"
      if [[ -n "${token}" ]]; then
        echo "http://127.0.0.1:${JLAB_LOCAL_PORT}/lab?token=${token}"
      else
        log "Jupyter token not found. Run: $0 start-jlab"
      fi
      return 0
    fi
    sleep 1
    ((i++))
  done
  log "Tunnel failed to start. Check /tmp/jlab-tunnel.log"
  tail -20 /tmp/jlab-tunnel.log >&2 || true
  exit 1
}

status() {
  local iid
  iid="$(get_instance_id || true)"
  if [[ -z "${iid}" ]]; then
    instance_not_bound_help
    exit 0
  fi
  awsq ec2 describe-instances \
    --instance-ids "${iid}" \
    --query 'Reservations[0].Instances[0].{InstanceId:InstanceId,State:State.Name,PublicIp:PublicIpAddress,Type:InstanceType,Name:Tags[?Key==`Name`]|[0].Value}' \
    --output table
}

list_instances() {
  awsq ec2 describe-instances \
    --filters Name=instance-state-name,Values=pending,running,stopping,stopped \
    --query 'sort_by(Reservations[].Instances[], &LaunchTime)[].{InstanceId:InstanceId,State:State.Name,Name:Tags[?Key==`Name`]|[0].Value,Type:InstanceType,PublicIp:PublicIpAddress,LaunchTime:LaunchTime}' \
    --output table
}

bootstrap() {
  require_cmd aws
  require_cmd ssh
  require_cmd curl

  if [[ -n "${S3_BUCKET}" ]]; then
    local bucket_name
    bucket_name="$(s3_bucket_name "${S3_BUCKET}")"
    S3_BUCKET="$(s3_bucket_uri "${S3_BUCKET}")"
    S3_CACHE_PREFIX="$(s3_cache_prefix_for "${S3_BUCKET}")"
    export S3_BUCKET S3_CACHE_PREFIX
    ensure_s3_bucket "${bucket_name}"
    ensure_iam_instance_profile_for_bucket "${bucket_name}"
  fi

  ensure_key_pair
  ensure_security_group >/dev/null
  ensure_instance >/dev/null
  start_instance
  ensure_eip
  write_ssh_config
  if [[ -n "${S3_BUCKET}" ]]; then
    attach_instance_profile
  fi
  status
  start_jlab
  start_tunnel

  local token
  token="$(ssh "${HOST_ALIAS}" "cat ~/.jlab/token")"
  echo
  echo "Open JupyterLab:"
  echo "http://127.0.0.1:${JLAB_LOCAL_PORT}/lab?token=${token}"
  if [[ -n "${S3_CACHE_PREFIX}" ]]; then
    echo "S3 public-data cache: ${S3_CACHE_PREFIX}"
    echo "On the instance: python3 scripts/download_public_data.py --references hg38 --s3-cache-prefix ${S3_CACHE_PREFIX}"
  fi
}

usage() {
  cat <<EOF
Usage: $0 <command> [args]

Bring your own EC2 (typical):
  $0 list-instances
  $0 use <instance-id-or-name>
  $0 up
  ssh ${HOST_ALIAS}

One-shot start + SSH config:
  $0 up <instance-id-or-name>
  $0 connect [instance-id-or-name]

Lifecycle:
  status | start-instance | stop-instance | reboot-instance

JupyterLab:
  start-jlab | stop-jlab | start-tunnel

Create a new EC2 for this project:
  bootstrap
  S3_BUCKET=s3://<your-bucket> $0 bootstrap
  S3_BUCKET=s3://<your-bucket> $0 attach-s3

If you can reach the instance via Instance Connect but not SSH:
  $0 use <instance-id>
  $0 install-my-key

Optional env vars:
  REGION, INSTANCE_ID, INSTANCE_NAME, HOST_ALIAS, SSH_USER, KEY_PATH
  KEY_NAME, KEY_OWNER (bootstrap key pair is per IAM user, not account-wide)
  AMI_ID (AL2023 x86_64 AMI id for bootstrap; default: SSM, then describe-images)
  INSTANCE_TYPE, ROOT_VOLUME_GB (bootstrap only; default 200)
  ROOT_VOLUME_IOPS, ROOT_VOLUME_THROUGHPUT_MB (bootstrap only; default 4000 / 1000)
  S3_BUCKET (e.g. s3://<your-bucket>) — grant the instance IAM access to this bucket
  S3_CACHE_PREFIX (default: s3://<bucket>/public)
  IAM_INSTANCE_PROFILE, IAM_ROLE_NAME
EOF
}

# Internal test hook: lets the test suite exercise `resolve_ami` directly
# without adding a public subcommand. Whitelisted; unused in normal operation.
if [[ -n "${EC2_JLAB_TEST_FN:-}" ]]; then
  case "${EC2_JLAB_TEST_FN}" in
    resolve_ami) resolve_ami ;;
    *) log "Unknown EC2_JLAB_TEST_FN: ${EC2_JLAB_TEST_FN}"
       exit 1
       ;;
  esac
  exit $?
fi

case "${1:-help}" in
  help|-h|--help) usage ;;
  bootstrap) bootstrap ;;
  use|bind-instance) bind_instance "${2:-}" ;;
  up) up "${2:-}" ;;
  connect) connect "${2:-}" ;;
  list-instances) list_instances ;;
  start-instance) start_instance ;;
  stop-instance) stop_instance ;;
  reboot-instance) reboot_instance ;;
  ensure-eip) ensure_eip ;;
  ssh-config) write_ssh_config ;;
  resolve-ip) get_public_ip ;;
  ssh-proxy)
    if [[ "${2:-}" =~ ^i-[0-9a-f]+$ ]]; then
      ssh_proxy "${3:-22}"
    else
      ssh_proxy "${2:-22}"
    fi
    ;;
  start-jlab) start_jlab ;;
  stop-jlab) stop_jlab ;;
  start-tunnel) start_tunnel ;;
  attach-s3) attach_instance_profile ;;
  install-my-key) install_my_key ;;
  status) status ;;
  *)
    usage
    exit 1
    ;;
esac
